### ISSUE TITLE
I found that  problems emerged while EJS were dealing with a little complicated expression.

### ISSUE THREAD

**Issue by tosone** [mde/ejs#133]
I found that  problems emerged while EJS were dealing with a little complicated expression such as 
```
<a href="/" <%= (currpage === 1) ? "class=ban" : "" %>>首页</a>
<a href="/<%= (currpage > 1) ? ("?page=" + (currpage - 1)) : "" %>" <%= (currpage > 1) ? "" : "class=ban" %>>上一页</a><span><%= currpage %> / <%= count %></span>
<a href="/<%= (currpage < count) ? ("?page=" + (currpage + 1)) : ("?page=" + count) %>" <%= (currpage < count) ? "" : "class=ban" %>>下一页</a>
<a href="/<%= "?page=" + count %>" <%= (currpage < count) ? "" : "class=ban" %>>尾页</a>
```
That is in my page. I exactly know that `currage` is defind, and my page had got its value, but the console gives me a error:
```
ReferenceError: currpage is not defined
      at eval (eval at <anonymous> (F:\code\coding\snippets\node_modules\koa-ejs\node_modules\ejs\lib\ejs.js:485:12), <anonymous>:30:9)
      at returnedFn (F:\code\coding\snippets\node_modules\koa-ejs\node_modules\ejs\lib\ejs.js:514:17)
      at render (F:\code\coding\snippets\node_modules\koa-ejs\index.js:89:15)
      at next (native)
      at Object.app.context.render (F:\code\coding\snippets\node_modules\koa-ejs\index.js:98:16)
      at next (native)
      at onFulfilled (F:\code\coding\snippets\node_modules\koa\node_modules\co\index.js:65:19)
```

If you want to get detail information you can review this repo : [repo](https://github.com/tosone/snippets.git)

**Comment by RyanZim** [comment]
How are you defining `currpage`?

**Comment by tosone** [comment]
```
router.get("/", function*(req, res, next) {
    let page = parseInt(this.query.page) ? parseInt(this.query.page) : 1;
    page = page <= 1 ? 1 : page;
    yield this.render('index', {
        code: yield model.findCode(page - 1),
        currpage: page,
        count: yield model.count()
    });
});
```

**Comment by RyanZim** [comment]
@mde & @TimothyGu  this is beyond me. Can one of you take over?

**Comment by tosone** [comment]
i know what is wrong with it. My fault, not EJS.
