### ISSUE TITLE
ejs with v0.11.14   Error: Identifier 'rethrow' has already been declared   

### ISSUE THREAD

**Issue by demohi** [mde/ejs#21]
```bash
$ node --version 
$ v0.11.14
```

some.js
```javascript
var ejs = require('ejs'); 
```

```bash
$ node --harmony some.js
```
Error
``` 
SyntaxError: Identifier 'rethrow' has already been declared
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mdemo/work/code/lark-views/ejs.js:9:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

**Comment by demohi** [comment]
#22

**Comment by mde** [comment]
Thanks for catching this! Reimplementing the missing v1 features was a big scramble. :) I've fixed this in a way that's consistent with the rest of the code (we're using expressions everywhere for functions) in 9f4797707cd6d6c905d6c2931420ec3d3ff05fd8 Pushed to NPM, v2.1.4.

**Comment by TimothyGu** [comment]
@mde Any reason why you changed it to a function exp instead of changing all functions to func decls?

**Comment by mde** [comment]
All things being equal, it's generally better to make fewer changes than more. :)

And I have generally come to prefer expressions because they just have normal hoisted variables. With declarations, the declared variable and the assignment are both hoisted, which adds another potentially confusing wrinkle. ... Or maybe it's just that declarations remind me of the bad old days of late 90s JS programming. :)
