### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by MichaelUyy** [mde/ejs#216]
I have a Node.JS application that is hosted on Ubuntu 16.04. I am using EJS to display queried data from MySQL but I am getting a reference error like this

    ReferenceError: /home/michaeluy/apps/michaeluy.me/views/index.html:130
     128| </div><br/><br/>
     129|         
      >> 130| <%=sec%>
      131| </div>
     132| </div>
     133| </body>

     sec is not defined
     at eval (eval at compile (/home/michaeluy/apps/michaeluy.me/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:11:23)
     at returnedFn (/home/michaeluy/apps/michaeluy.me/node_modules/ejs/lib/ejs.js:514:17)
     at View.exports.renderFile [as engine] (/home/michaeluy/apps/michaeluy.me/node_modules/ejs/lib/ejs.js:358:31)
     at View.render (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/view.js:126:8)
     at tryRender (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/application.js:639:10)
     at EventEmitter.render (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/application.js:591:3)
     at ServerResponse.render (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/response.js:961:7)
     at /home/michaeluy/apps/michaeluy.me/server.js:15:9
     at Layer.handle [as handle_request] (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/layer.js:95:5)
     at next (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/route.js:131:13)`

and here the first bit of my server.js file

    var http = require('http');
     var express = require('express');
    var fs = require('fs');
    var bodyParser = require('body-parser');
    var mysql = require('mysql');
    var connection  = require('express-myconnection');
    var app = express();

    app.use('/',express.static(__dirname + '/'));
    app.use(bodyParser.urlencoded({ extended: false }));
    app.engine('.html', require('ejs').__express);
    app.set('view engine','html');

    var connection = mysql.createConnection({
        host: '127.0.0.1',
        user: 'root',
        password: '',
        database: 'michaeluy'
    });

     app.get('/', function(req, res){
        connection.query("SELECT * FROM messages", function(err, rows, fields){
            if (err) throw err;
            res.render('index', {
                sec: rows[0].name
            });
        });
     });

I have tried using console.log at first to see if it is able to query the data correctly and it did but when I set the code on the html file for it to show up on the page itself. It gives back a reference error.

Hope someone can help here. Thanks in advance`

**Comment by mde** [comment]
Maybe it's the way you've set up the view engine.

I have a small Express app (v4.13.4) with EJS (v2.5.2), and this code words correctly:

```javascript
'use strict';

let express = require('express');
let app = express();

// Serve static files out of /public
app.use(express.static('public'));
app.set('view engine', 'ejs');

app.get('/foo', function (req, res) {
  res.render('foo', {
    bar: 'BAR'
  });
});

app.listen(8000, function () {
  console.log('Example app listening on port 8000!');
});
```

When I hit `http://localhost:8000/foo`, I see the "Howdy BAR" output as expected. I have a foo.ejs file in the "views" directory in the app.

**Comment by RyanZim** [comment]
> Maybe it's the way you've set up the view engine.

That's what I suspect; though I don't know for sure.

**Comment by MichaelUyy** [comment]
I have tried changing my view engine to ejs and it is giving back an error like this




    Error: Failed to lookup view "index" in views directory "/home/michaeluy/apps/michaeluy.me/views"
       at EventEmitter.render (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/application.js:579:17)
       at ServerResponse.render (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/response.js:961:7)
       at /home/michaeluy/apps/michaeluy.me/server.js:15:9
       at Layer.handle [as handle_request] (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/layer.js:95:5)
       at next (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/route.js:131:13)
       at Route.dispatch (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/route.js:112:3)
       at Layer.handle [as handle_request] (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/layer.js:95:5)
       at /home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/index.js:277:22
       at Function.process_params (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/index.js:330:12)
       at next (/home/michaeluy/apps/michaeluy.me/node_modules/express/lib/router/index.js:271:10)

**Comment by RyanZim** [comment]
@MichaelUyy What is the contents of `/home/michaeluy/apps/michaeluy.me/views`?

**Comment by MichaelUyy** [comment]
@RyanZim Here are the contents of that directory: https://github.com/MichaelUyy/michaeluyme/tree/master/views

**Comment by RyanZim** [comment]
@MichaelUyy I think you need to rename the `.html` files to an `.ejs` extension.

**Comment by MichaelUyy** [comment]
@RyanZim I also did that but it still results to that error

**Comment by RyanZim** [comment]
I cloned your repo, and it works fine for me; not sure what the issue is.

Try `console.log`ing the result of the database query, and make sure that your are getting the correct data there.

**Comment by MichaelUyy** [comment]
@RyanZim I have tried to add a console.log the app.get for index but it did not return a value.

I had it set like this


    app.get('/', function(req, res){
    connection.query("SELECT * FROM messages", function(err, rows, fields){
        if (err) throw err;
        console.log(rows[0].name);
        res.render('index', {
            sec: rows[0].name
        });
    });
});

and I ran the command 



    DEBUG=express:* node server.js

just to see whether it is showing but it didn't. However, if I create a query and place a console.log outside app.get. It is able to provide me with an output

**Comment by RyanZim** [comment]
@MichaelUyy Not sure what's going on here; either way, I think this is a database issue, not EJS.

**Comment by MichaelUyy** [comment]
@RyanZim I am not entirely sure regarding the database issue since I am able to query data as long as it is outside any of the app.get's. Anyways, thanks for the help. I'll try to see what I can do

**Comment by MacgyverMartins** [comment]
I am having the same error here
