### ISSUE TITLE
When compiled by 'client: true' and call template then 'utils is not defined' occurred.

### ISSUE THREAD

**Issue by uk-taniyama** [mde/ejs#229]
utils.escapeXML => escape ?

```
function anonymous(locals, escape, include, rethrow
/**/) {
rethrow = rethrow || function rethrow(err, str, flnm, lineno){
  var lines = str.split('\n');
  var start = Math.max(lineno - 3, 0);
  var end = Math.min(lines.length, lineno + 3);
  var filename = utils.escapeXML(flnm);
  // Error context
  var context = lines.slice(start, end).map(function (line, i){
    var curr = i + start + 1;
    return (curr == lineno ? ' >> ' : '    ')
      + curr
      + '| '
      + line;
  }).join('\n');

  // Alter exception message
  err.path = filename;
  err.message = (filename || 'ejs') + ':'
    + lineno + '\n'
    + context + '\n\n'
    + err.message;

  throw err;
};
```

**Comment by RyanZim** [comment]
@uk-taniyama I'm not sure what your issue is. Please post a minimal example demonstrating your problem. Thanks!

**Comment by uk-taniyama** [comment]
Thanks > @RyanZim 

Source is.

```
var ejs = require('ejs');
var template = ejs.compile('<% throw "ERROR" %>', {client:true});
console.log(template.toString());
template();
```

Result by node.js

```
function anonymous(locals, escape, include, rethrow
/**/) {
rethrow = rethrow || function rethrow(err, str, flnm, lineno){
  var lines = str.split('\n');
  var start = Math.max(lineno - 3, 0);
  var end = Math.min(lines.length, lineno + 3);
  var filename = utils.escapeXML(flnm);
  // Error context
  var context = lines.slice(start, end).map(function (line, i){
    var curr = i + start + 1;
    return (curr == lineno ? ' >> ' : '    ')
      + curr
      + '| '
      + line;
  }).join('\n');

  // Alter exception message
  err.path = filename;
  err.message = (filename || 'ejs') + ':'
    + lineno + '\n'
    + context + '\n\n'
    + err.message;

  throw err;
};
escape = escape || function (markup) {
  return markup == undefined
    ? ''
    : String(markup)
        .replace(_MATCH_HTML, encode_char);
};
var _ENCODE_HTML_RULES = {
      "&": "&amp;"
    , "<": "&lt;"
    , ">": "&gt;"
    , '"': "&#34;"
    , "'": "&#39;"
    }
  , _MATCH_HTML = /[&<>'"]/g;
function encode_char(c) {
  return _ENCODE_HTML_RULES[c] || c;
};
;
var __line = 1
  , __lines = "<% throw \"ERROR\" %>"
  , __filename = undefined;
try {
  var __output = [], __append = __output.push.bind(__output);
  with (locals || {}) {
    ;  throw "ERROR"
  }
  return __output.join("");
} catch (e) {
  rethrow(e, __lines, __filename, __line);
}

}
undefined:7
  var filename = utils.escapeXML(flnm);
                 ^

ReferenceError: utils is not defined
    at rethrow (eval at compile (C:\projects\webpack-test2\node_modules\ejs\lib\ejs.js:481:12), <anonymous>:7:18)
    at eval (eval at compile (C:\projects\webpack-test2\node_modules\ejs\lib\ejs.js:481:12), <anonymous>:54:3)
    at Object.<anonymous> (C:\projects\webpack-test2\ejs.test.js:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

**Comment by RyanZim** [comment]
That does look weird, not real familiar with that part of the code; @mde @TimothyGu any insight?

**Comment by mde** [comment]
This is a regression caused by the previous set of security fixes. Fixed in aa1771e, will go out in the next release.

**Comment by SanderElias** [comment]
Hi @mde, I'm having the same issue, are you going to cut a release soon, or should I pull from github for the time being?

**Comment by mde** [comment]
We have a couple of optimizations in the pipe. I'd like to batch stuff, so I figure a release sometime next week.

**Comment by leeeco610** [comment]
I'm having the same issue

**Comment by mde** [comment]
Pushed out in v2.5.6: https://github.com/mde/ejs/releases/tag/v2.5.6
