### ISSUE TITLE
Including doesn't work on Windows

### ISSUE THREAD

**Issue by leongrdic** [mde/ejs#305]
The code I tried running (app.js):
`
var ejs = require('ejs');
var result = ejs.render("<% include test.html %>");
console.log(result);
`

Error message:
`
Error: Could not find include include file.
    at getIncludePath (Z:\Twmp\node_modules\ejs\lib\ejs.js:152:13)
    at includeSource (Z:\Twmp\node_modules\ejs\lib\ejs.js:276:17)
    at Z:\Twmp\node_modules\ejs\lib\ejs.js:629:26
    at Array.forEach (native)
    at Object.generateSource (Z:\Twmp\node_modules\ejs\lib\ejs.js:605:15)
    at Object.compile (Z:\Twmp\node_modules\ejs\lib\ejs.js:509:12)
    at Object.compile (Z:\Twmp\node_modules\ejs\lib\ejs.js:358:16)
    at handleCache (Z:\Twmp\node_modules\ejs\lib\ejs.js:201:18)
    at Object.exports.render (Z:\Twmp\node_modules\ejs\lib\ejs.js:384:10)
    at Object.<anonymous> (Z:\Twmp\app.js:3:18)
`

The test.html file is in the same directory as the app.js
I even tried passing the current directory as a root option with windows `\` separators and even unix `/` but then I get the following error message:
`
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at dirname (path.js:695:5)
    at Object.exports.resolveInclude (Z:\Twmp\node_modules\ejs\lib\ejs.js:109:48)
    at Z:\Twmp\node_modules\ejs\lib\ejs.js:647:44
    at Array.forEach (native)
    at Object.generateSource (Z:\Twmp\node_modules\ejs\lib\ejs.js:605:15)
    at Object.compile (Z:\Twmp\node_modules\ejs\lib\ejs.js:509:12)
    at Object.compile (Z:\Twmp\node_modules\ejs\lib\ejs.js:358:16)
    at handleCache (Z:\Twmp\node_modules\ejs\lib\ejs.js:201:18)
    at Object.exports.render (Z:\Twmp\node_modules\ejs\lib\ejs.js:384:10)
`

The only way I got it to work was this:
`
ejs.render("<% include /test.html %>);
`
and changing the 109th line in lib/ejs.js from
`var includePath = resolve(isDir ? filename : dirname(filename), name);`
to
`var includePath = name;`
but I suppose that's not how it's meant to be.

Could anyone suggest a fix? The problem is obviously laying somewhere in the 109th line.
Any help appreciated

**Comment by leongrdic** [comment]
My bad, I didn't realize that I should be using `options.filename` when the path isn't absolute. Closing the issue.
