### ISSUE TITLE
Could not find matching close tag for "<%-".

### ISSUE THREAD

**Issue by axelrindle** [mde/ejs#389]
## Description
I have two `.ejs` files:

#### sidebar_item.ejs
```ejs
<a class="item <%- currentPath.wantClass('<%= path %>', '<%= class %>') %>" href="<%= path %>">
  <%= title %>
</a>
```

#### sidebar.ejs
```ejs
<!-- Sidebar -->
<div class="col-3 sidebar padded--horizontal">

  <h1>
    <a class="no-border" href="<%- basePath %>">
      <img class="width-100" src="<%- asset('img/logo.svg') %>"></a>
  </h1>

  <div class="menu space--top__big width-100">
    <%- include('partials/sidebar_item', { title: 'Dashboard', path: '/', class: 'active' }) %>
    <%- include('partials/sidebar_item', { title: 'Create Project', path: '/project/create/', class: 'active' }) %>
    <%- include('partials/sidebar_item', { title: 'Settings', path: '/settings/', class: 'active' }) %>
  </div>

</div> <!-- end .sidebar -->
```

When trying to compile the layout with the given `include` directives, I receive the following error output as seen below.

In my eyes there is nothing missing. What is going on?

## Error Output
```
/home/axel/Schreibtisch/Projekte/adamci/frontend/views/partials/sidebar.ejs:10
    8| 
    9|   <div class="menu">
 >> 10|     <%- include('partials/sidebar_item', { title: 'Dashboard', path: '/', class: 'active' }) %>
    11|     <%- include('partials/sidebar_item', { title: 'Create Project', path: '/project/create/', class: 'active' }) %>
    12|     <%- include('partials/sidebar_item', { title: 'Settings', path: '/settings/', class: 'active' }) %>
    13|   </div>

Could not find matching close tag for "<%-".
    at /home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:693:19
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:678:15)
    at Template.compile (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:557:12)
    at Object.compile (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:389:16)
    at handleCache (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:212:18)
    at includeFile (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:289:10)
    at include (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:651:16)
    at eval (eval at compile (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:24:17)
    at eval (eval at compile (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:36:10)
    at returnedFn (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:653:17)
    at tryHandleCache (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/home/axel/Schreibtisch/Projekte/adamci/node_modules/ejs/lib/ejs.js:482:10)
    at View.render (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express/lib/response.js:1008:7)
    at ServerResponse.res.render (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express-ejs-layouts/lib/express-layouts.js:77:18)
    at ServerResponse.res.render (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express-flash/lib/express-flash.js:29:16)
    at module.exports (/home/axel/Schreibtisch/Projekte/adamci/backend/routes/home.js:3:7)
    at Layer.handle [as handle_request] (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/axel/Schreibtisch/Projekte/adamci/node_modules/express/lib/router/route.js:137:13)
```

## Versions used
- `ejs 2.6.1`
- `express 4.16.3`

**Comment by axelrindle** [comment]
Fixed by myself, this was caused by an issue in another file where is used nested control flows.

**Comment by sagarsureka** [comment]
Hi! I am having the same issue as above. I have a single ejs file `home.ejs`. The following is the only section of the file that makes use of the `<%` tags.

<img width="803" alt="Screenshot 2020-10-22 at 7 22 15 PM" src="https://user-images.githubusercontent.com/54656024/96881597-1124a500-149c-11eb-92d8-8aebd4713aea.png">

Here, data is an array containing documents retrieved from the database. Each document contains a field called `module`.

The error I receive when the code tries to execute the ejs file is more or less the same as the screenshot above. 

<img width="704" alt="Screenshot 2020-10-22 at 7 19 25 PM" src="https://user-images.githubusercontent.com/54656024/96881933-619c0280-149c-11eb-9e85-4835e3929987.png">

I think the problem maybe in one of the lines in the stack trace above. Since you managed to solve this, would it be okay to ask for some help in this regard?

Thanks!

### Versions Used

`ejs` : 3.1.5
`express` : 4.17.1

**Comment by analyceferreira** [comment]
I have the same problem
can you share the code of how you fixed it?

**Comment by Mayank8451** [comment]
same problem

**Comment by gabrielfiorotti** [comment]
same problem
