### ISSUE TITLE
Compiled template exceeding maximum JS string length

### ISSUE THREAD

**Issue by fleupold** [mde/ejs#394]
I'm using ejs to compile a relatively short template (150 lines) into a very large file  (>>10M lines) that I want to write to disk.

I'm running into the following crash:

```
Invalid string length
    at Array.join (native)
    at eval (eval at compile (/.../node_modules/ejs/lib/ejs.js:618:12), <anonymous>:191:19)
    at returnedFn (/.../node_modules/ejs/lib/ejs.js:653:17)
    at /.../node_modules/ejs/lib/ejs.js:237:40
    at new Promise (<anonymous>)
    at tryHandleCache (/.../node_modules/ejs/lib/ejs.js:235:14)
    at Object.exports.renderFile (/.../node_modules/ejs/lib/ejs.js:482:10)
    at Object.<anonymous> (/.../codegen/generate.js:21:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

I believe this is due to the [size-limit of string in V8](https://bugs.chromium.org/p/v8/issues/detail?id=6148#c10) and the fact that ejs returns the compiled template as a string.

Is it somehow possible to return the compiled template as a Buffer or stream it directly into a file?

If not, would this be theoretically possible or are there operations that need to happen on the fully compiled template string?

**Comment by fleupold** [comment]
Turns out [ejs-promise](https://www.npmjs.com/package/ejs-promise) has this functionality. Feel free to close if this is something you don't feel is worth adding.
