### ISSUE TITLE
fileLoader is undefined

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [mde/ejs#447]
Hi! Using 2.6.1 and found myself in a funky situation.
Wrote a very barebones NodeJS server without express to study more Node and when I attempted to use ejs to handle some of the templating work I came accross this:

```js
import fs from "fs";
import ejs from "ejs";
import { 
  validateString,
  validateObjectWithDefault
} from "./validators";
import CONFIG from "../webServer/config.web_server";


// TODO: Improve template errors:

export const getTemplate = (templateName, data, cb) => {
  templateName = validateString(templateName);
  data         = validateObjectWithDefault(data);
  console.log(ejs);
  return templateName
    ? ejs.renderFile(
        `${CONFIG.templateDir}/${templateName}.ejs`,
        data,
        {},
        (err, str) => {
          console.log(err);
          console.log(str);
          return !err && str && str.length > 0
          ? cb(false, str)
          : cb("Error: No template found");
        })
    : cb("Error: Invalid template name"); 
};
```

Which then curiously outputs this:

```
{ cache:
   { _data: {},
     set: [Function: set],
     get: [Function: get],
     remove: [Function: remove],
     reset: [Function: reset] },
  fileLoader: undefined,
  localsName: 'locals',
  promiseImpl: [Function: Promise],
  resolveInclude: [Function],
  compile: [Function],
  render: [Function],
  renderFile: [Function],
  Template:
   { [Function: x]
     modes:
      { EVAL: 'eval',
        ESCAPED: 'escaped',
        RAW: 'raw',
        COMMENT: 'comment',
        LITERAL: 'literal' } },
  clearCache: [Function],
  escapeXML: { [Function] toString: [Function] },
  __express: [Function],
  VERSION: '2.6.1',
  name: 'ejs' }
TypeError: n.fileLoader is not a function
    at g (D:\Projects\JavaScript\NodeJSMasterClass\WebApp\server\build\main.js:13:1050)
    at v (D:\Projects\JavaScript\NodeJSMasterClass\WebApp\server\build\main.js:13:945)
    at D:\Projects\JavaScript\NodeJSMasterClass\WebApp\server\build\main.js:13:3292
    at Object.n.renderFile (D:\Projects\JavaScript\NodeJSMasterClass\WebApp\server\build\main.js:13:3331)
    at S.n.head.initialState (D:\Projects\JavaScript\NodeJSMasterClass\WebApp\server\build\main.js:1:181173)
    at S (D:\Projects\JavaScript\NodeJSMasterClass\WebApp\server\build\main.js:1:181380)
    at IncomingMessage.<anonymous> (D:\Projects\JavaScript\NodeJSMasterClass\WebApp\server\build\main.js:1:198785)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
undefined
```
I was under the impression that a fileLoader should be set by default, but now this seems to be missing? As you can probably guess from the imports, I'm using webpack to transpile, could this affect?

**Comment by 4lph4-Ph4un** [comment]
Anything? Anyone? :D

**Comment by 4lph4-Ph4un** [comment]
Okay! Some progress with the issue. Noticed that fileLoader is is found again if I remove:

```javascript
resolve: {
  alias: {
    "ejs": "ejs/ejs.min.js"
  }
},
```

..from my webpack config. However this results in a another issue where ejs-files are not found on their location, although they exist.

**Comment by mde** [comment]
Sorry for the late reply on this issue. It's been a busy week. It's always difficult to troubleshoot problems with integrations with EJS. Most of the time, it's environmental, as you noted — although the reference to the .min.js file would seem to indicate some confusion about whether you're using EJS client- or server-side.

**Comment by 4lph4-Ph4un** [comment]
Yes, absolutely! That was the exact case. The other issue was just my own silliness (just deriving a malformed path from configurations). I was also a bit side-track because of the `require.extensions`-warning but found info about it from other issues. Originally whipped out aliasing to silence that, but stand now corrected :)
