### ISSUE TITLE
ejs.renderFile is not working when table rows are 10 million.

### ISSUE THREAD

**Issue by mishrasatyam** [mde/ejs#474]
Error:
`RangeError: test.ejs:16
    14|     </body>
    15| </html>
 >> 16| 

Invalid string length
    at Array.join (<anonymous>)
    at eval (eval at compile (/home/bbiadmi/test_template_engines/node_modules/ejs/lib/ejs.js:1:1), <anonymous>:27:19)
    at returnedFn (/home/bbiadmi/test_template_engines/node_modules/ejs/lib/ejs.js:668:17)
    at tryHandleCache (/home/bbiadmi/test_template_engines/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/home/bbiadmi/test_template_engines/node_modules/ejs/lib/ejs.js:485:10)
    at generate_data (/home/bbiadmi/test_template_engines/test2.js:9:5)
    at Object.<anonymous> (/home/bbiadmi/test_template_engines/test2.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  path: 'test.ejs'
}`

Below is test.ejs:
`<html>`
    `<body>`
        `<table>`
            `<tbody>`
                `<% let c = 0 %>`
                `<% while(c<10000000){ %>`
                `<% c+=1 %>`    
                `<tr>`
                    `<td><%= c %></td>`
                `</tr>`
                `<% } %>`
            `</tbody>`
        `</table>`
    `</body>`
`</html>`

Below is code:

`ejs.renderFile('test.ejs',context,async function(error,str){
    if(error) {console.log(error)}
    await fs.writeFile('pop.html',str,(err) => {if(err)console.log(err)})
  })`

The code is working fine when number of rows are 9 million but it fails when it is 10 million.

**Comment by ExE-Boss** [comment]
**JavaScript** strings have a&nbsp;length limit of&nbsp;<code>2<sup>53</sup> ‑ 1</code> (the&nbsp;[maximum&nbsp;safe&nbsp;integer](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) representable in&nbsp;a&nbsp;**JavaScript**&nbsp;`number`), in&nbsp;this&nbsp;case the&nbsp;generated&nbsp;**HTML** is&nbsp;longer&nbsp;than&nbsp;that.
