### ISSUE TITLE
Crash on missing file

### ISSUE THREAD

**Issue by mindeavor** [mde/ejs#5]
The following code tries to render a file that does not exist:

```javascript
ejs.renderFile(__dirname + '/app/index.html.ejs')
```

...but you can't discern that from the resulting error message:

```
./node_modules/ejs/lib/ejs.js:213
      var tmpl = data.toString().trim();
                      ^
TypeError: Cannot call method 'toString' of undefined
    at ./node_modules/ejs/lib/ejs.js:213:23
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
```

The problem lies in this library's code using `data` before it checks for `err`:

```javascript
    read(path, function (err, data) {
      var tmpl = data.toString().trim();
      if (err) {
        return cb(err);
      }
      if (opts.cache) {
        templateCache[path] = tmpl;
      }
      handleTemplate(tmpl);
    });
```

**Comment by mde** [comment]
Fix pushed to NPM in v2.0.8. Thanks for catching this!
