### ISSUE TITLE
CLI throw error because usage.txt not found

### ISSUE THREAD

**Issue by weibangtuo** [mde/ejs#516]
node: v12.16.1
npm: 6.13.14
ejs: 3.1.2(latest)

Steps:
1. run `npm install -g ejs@3.1.2`
2. run `ejs -h` or some other commands

Output:
```
➜  ~ ejs -h
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/ejs/bin/../usage.txt'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/ejs/bin/cli.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/ejs/bin/../usage.txt'
}
```

Every CLI command throw the error and create `usage.txt` file under `node_modules/ejs` to be fixed. Please check the npm publishing packages.

**Comment by mde** [comment]
Fixed in commit d434f459872eaf97143a7e1cdb853a80f06b13c3 and pushed to NPM in version 3.1.3. Thank you very much for catching this!
