### ISSUE TITLE
rendering static files from express+EJS app?

### ISSUE THREAD

**Issue by kylebakerio** [mde/ejs#520]
I first started playing with EJS in Hexo, and became fond of it. In that context, you render out a 'public' folder that you can just drop onto a dirt-simple fileserver and you get a clean static site.

So for a new project (covid.kylebaker.io), knowing I needed a server this time, I saw that express-create-app offered EJS support out of the box, so I went with that, and it has been a pleasant experience overall.

However, I'm toying with an idea, and I want to know how to bridge this gap. Currently, the only way I get html out is through the express app. How could I produce something like hexo, a rendered static output?

I tried looking around, seems like the CLI should enable it, but it looks like it's not able to resolve the relative filepaths I think?

```
ejs /home/kyle/code/corona/corona-server/views/analysis.ejs -o test.html
/usr/local/lib/node_modules/ejs/lib/ejs.js:359
  throw err;
  ^

Error: ejs:1
 >> 1| <%- include("_partials/base", {
    2|     page:"analysis",
    3|     combo:["ionrangeslider"],
    4|     scripts: ["analysis"],

Could not find the include file "_partials/base"
    at getIncludePath (/usr/local/lib/node_modules/ejs/lib/ejs.js:183:13)
    at includeFile (/usr/local/lib/node_modules/ejs/lib/ejs.js:309:19)
    at include (/usr/local/lib/node_modules/ejs/lib/ejs.js:689:16)
    at eval (eval at compile (/usr/local/lib/node_modules/ejs/lib/ejs.js:661:12), <anonymous>:10:17)
    at anonymous (/usr/local/lib/node_modules/ejs/lib/ejs.js:691:17)
    at Object.exports.render (/usr/local/lib/node_modules/ejs/lib/ejs.js:423:37)
    at Immediate.run (/usr/local/lib/node_modules/ejs/bin/cli.js:197:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

What's the right way to do something like this?

Thanks!

**Comment by kylebakerio** [comment]
I ended up answering my own question here: https://stackoverflow.com/questions/62152600/using-express-ejs-how-can-i-render-as-a-static-site/62249791#62249791

**Comment by mde** [comment]
Sorry I didn't have a chance address this sooner. Glad you were able to figure this out.
