### ISSUE TITLE
 Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by cesine** [mde/ejs#534]
# Steps to reproduce

https://travis-ci.org/github/caolan/nodeunit/jobs/710077156

$ npm install 
npm WARN engine tap@12.7.0: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
> ejs@2.7.4 postinstall /home/travis/build/caolan/nodeunit/node_modules/ejs
> node ./postinstall.js
/home/travis/build/caolan/nodeunit/node_modules/ejs/postinstall.js:9
let envDisable = isTrue(process.env.DISABLE_OPENCOLLECTIVE) || isTrue(process.
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

# Root cause

 `let` was introduced in a patch version v2.7.2...v2.7.3  

# Impact

Several projects are unable to build, including 194 projects which depend directly on nodeunit which is an older "stale" project that was widely used on these older versions of node. 

# Solution

I can help make the patch if you can make a branch on the upstream to represent the `2.x` releases

(diff that would fix: https://github.com/cesine/ejs/pull/1)

**Comment by mde** [comment]
This issue has been closed as outdated. 

If you believe this issue is still relevant, please:
1. Open a new issue with current context
2. Reference this issue number (#534)
3. Include details about your use case and EJS version

Thank you for your contribution!
