### ISSUE TITLE
ejs file not recognizing variable

### ISSUE THREAD

**Issue by nst27** [mde/ejs#554]
ReferenceError: C:\node\secrets\views\secrets.ejs:7
    5|     <i class="fas fa-key fa-6x"></i>
    6|     <h1 class="display-3">You've Discovered My Secret!</h1>
 >> 7|     <% abc.forEach(function(user){ %>
    8|     <p class="secret-text"><%= user.secret %></p>
    9| 
    10|     <%}); %>

abc is not defined
    at eval (C:\node\secrets\views\secrets.ejs:11:8)
    at secrets (C:\node\secrets\node_modules\ejs\lib\ejs.js:691:17)
    at tryHandleCache (C:\node\secrets\node_modules\ejs\lib\ejs.js:272:36)
    at View.exports.renderFile [as engine] (C:\node\secrets\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (C:\node\secrets\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\node\secrets\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\node\secrets\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\node\secrets\node_modules\express\lib\response.js:1012:7)
    at C:\node\secrets\app.js:162:25
    at C:\node\secrets\node_modules\mongoose\lib\model.js:4843:16
    at C:\node\secrets\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    at C:\node\secrets\node_modules\mongoose\lib\model.js:4866:21
    at model.<anonymous> (C:\node\secrets\node_modules\mongoose\lib\model.js:502:7)
    at C:\node\secrets\node_modules\kareem\index.js:315:21
    at next (C:\node\secrets\node_modules\kareem\index.js:209:27)
    at C:\node\secrets\node_modules\kareem\index.js:182:9

MY CODE - 
app.get("/secrets",function(req,res){
    User.find({"secret":{$ne:null}},function(err,foundUser){
        if(err){
            console.log(err);
        }else{
            if(foundUser){
                console.log("hello");
                res.render("secrets",{abc:foundUser});
            }
        }
    });
});

**Comment by crossphoton** [comment]
Try printing the foundUser variables in your JS file. I suspect you're using MongoDB.
