### ISSUE TITLE
Simple EJS web app, getting: " SyntaxError: Unexpected token '/' "

### ISSUE THREAD

**Issue by enjoysmath** [mde/ejs#565]
Following the instructions here:

http://www.ashishblog.com/getting-start-with-arangodb-using-nodejs-nodejs-ejs-arangojs/

I'm getting the following printed in the browser when going to http://localhost:3000

```
SyntaxError: Unexpected token '/' in C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\views\error.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\ejs\lib\ejs.js:661:12)
    at Object.compile (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\ejs\lib\ejs.js:396:16)
    at handleCache (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\ejs\lib\ejs.js:233:18)
    at tryHandleCache (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\ejs\lib\ejs.js:272:16)
    at View.exports.renderFile [as engine] (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\FruitfulApproach\Desktop\Quiver\quiver\nodeArangoWebApp\node_modules\express\lib\response.js:1008:7)

```

My error.ejs looks like:

```

<% include ./partials/head %>
<main>
    <div class="jumbotron">
        <h1><%=message %></h1>
            <h2><%=error.status %><h2>
        <pre><%= error.stack %></pre>
    </div>
</main>
<% include ./partials/footer %>
```

Not sure what to do.

**Comment by RyanZim** [comment]
Your tutorial is outdated; preprocesser-style includes haven't been supported since v3.0 https://github.com/mde/ejs#includes
