### ISSUE TITLE
When I try to call a function in an include EJS file, I get a 'function is not defined' error

### ISSUE THREAD

**Issue by paultipper** [mde/ejs#590]
I have a couple of common functions that I want to be able to use in multiple EJS files, so I thought I'd code these in a separate utilities.ejs file, and then include the utilities.ejs file in any other EJS files that need to call its functions. I've coded utilities.ejs as follows:

```<% 

// EJS utility functions
// A reference to this file will be assigned to the ejsUtilities property in the links section 
// of the data passed to ejs.render in the handlers/transformDataHandler.js component,
// allowing it to be included in the EJS templates used to transform data

/**
 * 
*/
const roundValue = (value, decimalPlaces) => {
    const factorOfTen = Math.pow(10, decimalPlaces);
    return Math.round(value * factorOfTen) / factorOfTen;
}

const formatValue = (value, decimalPlaces) => value.toFixed(decimalPlaces);

%>
```

I then pass the full path of the utilities.ejs file into my main EJS file in the data, and include it as follows:

`<%- include(links.ejsUtilities) %>`

and then I invoke utility functions as follows:

`<td class="num"><%= formatValue(line.price, 2) %></td>`

However, when I call the ejs.Render method to transform my data into a HTML file, I get the following error:

```ReferenceError: ejs:59
    57|       <td class="produce"><%= line.description %></td>
    58|       <td class="num"><%= line.quantity %></td>
 >> 59|       <td class="num"><%= formatValue(line.price, 2) %></td>
    60|       <td class="num"><%= formatValue(line.value, 2) %></td>
    61|   </tr>
    62|       

formatValue is not defined
    at eval (eval at compile (/home/developer/sls-examples/document-generator/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:64:7)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (/home/developer/sls-examples/document-generator/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:54:7)
    at anonymous (/home/developer/sls-examples/document-generator/node_modules/ejs/lib/ejs.js:692:17)
    at Object.exports.render (/home/developer/sls-examples/document-generator/node_modules/ejs/lib/ejs.js:423:37)
    at /home/developer/sls-examples/document-generator/src/handlers/transformDataHandler.js:51:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  path: ''
```

Why is the `formatValue` function not in scope in the main EJS file? I've seen it suggested in a StackExchange post related to this issue that it's not possible to call any functions declared in include files directly in this way - is this true?

**Comment by RyanZim** [comment]
Yes, that's correct. `include` only includes the rendered result of the file you're including, not the scripting in the included file. The way to solve this is to pass your utility functions as locals in your render call.

**Comment by paultipper** [comment]
@RyanZim Thanks for the reply, Ryan - passing the functions in as properties of the `data` object to the `ejs.render()` method makes perfect sense. For the benefit of others encountering this issue, here's exactly how I did it:

1. I created an ejsUtilities.js component with my utility functions:

```
/**
 * EJS utility functions
 * These functions are passed into the ejs.render() function in the data parameter,
 * so can be used within the EJS template
 */

/**
 * Round a numeric value to the specified number of decimal places.
 * This function is passed into ejs.render(), so can be used within the EJS template.
 * @param {number} value
 * @param {integer} [decimalPlaces]
 * @returns {number} The value rounded to the specified number of decimal places
 */
const roundValue = (value, decimalPlaces = 2) => {
  const factorOfTen = Math.pow(10, decimalPlaces);
  return Math.round(value * factorOfTen) / factorOfTen;
};

/**
 * Return a numeric value as a string rounded to the specified number of decimal places.
 * This function is passed into ejs.render(), so can be used within the EJS template.
 * @param {number} value
 * @param {integer} [decimalPlaces]
 * @returns {string} A string representation of the numeric value, rounded to the requisite number of decimal places
 */
const formatValue = (value, decimalPlaces) => value.toFixed(decimalPlaces);

module.exports = { roundValue, formatValue };
```

2. I import these functions into my transformation component:

```
const ejsUtilities = require("../util/ejsUtilities");
```

3. I incorporate all of the functions in ejsUtilities.js into the data object that's passed to `ejs.render()` using the spread operator:

```
// Create the EJS data object for transformation by the EJS template
            const ejsData = {
              ...ejsUtilities,
              links: {
                cssSignedUrl,
                resourceUrls,
              },
              data,
            };

            // Transform the data into HTML using the EJS template definition
            const html = ejs.render(ejsTemplate, ejsData);

```

**Comment by RyanZim** [comment]
@paultipper Perfect; that's exactly what I had in mind, but didn't have time to write it out fully. Thanks for posting here for others' benefit.
