### ISSUE TITLE
SyntaxError With no Error

### ISSUE THREAD

**Issue by decodercc** [mde/ejs#597]
Hey!
Today I decided to move the site head, navigation and footer into separate files.
The first 3 hours everything worked EXCELLENT, then when you go to the page, it gives an error:
```
SyntaxError: /root/moonlist/dynamic/errors/express.ejs:9
    7 | </head>
    8 | <body>
 >> 9 | <% - include ('../ blocks / navbar', {bot, user})%>
    10 | <div class = "bigthingy row">
    11 | <div class = "seeme col-md-8 offset-md-2 row">
    12 | <div class = "seeme col-sm-2 sinfo">

missing) after argument list in /root/moonlist/dynamic/blocks/navbar.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/root/moonlist/node_modules/ejs/lib/ejs.js:661:12)
    at Object.compile (/root/moonlist/node_modules/ejs/lib/ejs.js:396:16)
    at handleCache (/root/moonlist/node_modules/ejs/lib/ejs.js:233:18)
    at includeFile (/root/moonlist/node_modules/ejs/lib/ejs.js:321:10)
    at include (/root/moonlist/node_modules/ejs/lib/ejs.js:689:16)
    at eval (/root/moonlist/dynamic/errors/express.ejs:13:17)
    at express (/root/moonlist/node_modules/ejs/lib/ejs.js:691:17)
    at tryHandleCache (/root/moonlist/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/root/moonlist/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/root/moonlist/node_modules/express/lib/view.js:135:8)
    at tryRender (/root/moonlist/node_modules/express/lib/application.js:640:10)
    at Function.render (/root/moonlist/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/root/moonlist/node_modules/express/lib/response.js:1012:7)
    at module.exports.renderTemplate (/root/moonlist/structures/middleware.js:28:7)
    at runMicrotasks (<anonymous>)
```
What to do, help!

**Comment by mde** [comment]
This is not a problem with the EJS lib. At first glance however, it appears that you have spaces in your file path for the `include` call. I am closing this. Feel free to open a new ticket if you have a problem that is actually in the EJS lib itself.
