### ISSUE TITLE
jake aborted - unable to make/build ejs

### ISSUE THREAD

**Issue by davidmoonraw** [mde/ejs#762]
Below is the error:

```
  269:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    270:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  
  ✖ 3343 problems (3343 errors, 0 warnings)
    3343 errors and 0 warnings potentially fixable with the '--fix' option.
  
  jake aborted.
  Error: Command failed: node_modules\.bin\eslint "**/*.js"
      at genericNodeError (node:internal/errors:984:15)
      at wrappedFn (node:internal/errors:538:14)
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at exec (C:\Users\davidmoonraw\Documents\dev\lens\client\ejs\jakefile.js:5:3)
      at Task.action (C:\Users\davidmoonraw\Documents\dev\lens\client\ejs\jakefile.js:24:3)
      at Task.run (C:\Users\davidmoonraw\Documents\dev\lens\node_modules\jake\lib\task\task.js:329:29)
      at process.processImmediate (node:internal/timers:478:21)
```

I've also come across:

`jake aborted.
Error: Unknown task "default"
    at Task.nextPrereq (C:\Users\davidmoonraw\Documents\dev\lens\node_modules\jake\lib\task\task.js:222:15)
    at process.processImmediate (node:internal/timers:478:21)`

Steps taken:

- Installed jake as devdependencies
- Installed jake as dependencies
- Edited `exec(epath+' "**/*.js"');` as just `/*.js`
- Reviewed **Issues**
- Checked _stackoverflow_ with **jake** tag
- Cross checked Chatgpt
- Followed readme instructions
- Tested absolute and relative paths
- Used npx

Kindly aasist

**Comment by phanect** [comment]
This seems the ESLint errors.
CRLF line breaks are included somewhere in this repo while it is forbidden by ESLint.

As a workaround, you can run `npx eslint --fix` to replace all the CRLF linebreaks with LF.

**Comment by davidmoonraw** [comment]
@phanect yeah it appears that included everywhere.  Looks like `linebreak-style deprecated` as per [Rules Reference](https://eslint.org/docs/latest/rules/) . Anyway can't be more obvious than what you mentioned. Thanks for your input.
