### ISSUE TITLE
uglify is not recognized

### ISSUE THREAD

**Issue by davidmoonraw** [mde/ejs#763]
Below is the error. I'm just trying to make a build. I have checked docs and searched around google/youtube. Kindly suggest

```
davidmoonraw@MSI MINGW64 ~/Documents/dev/foo/ejs (main)
$ ./node_modules/.bin/jake.cmd build jakefile.js --debug
Starting 'clobberPackage'...
Finished 'clobberPackage' after 1 ms
Starting 'clobber'...
Finished 'clobber' after 0 ms
Starting 'clean'...
Cleaned up compiled files.
Finished 'clean' after 1 ms
Starting 'lint'...
Linting completed.
Finished 'lint' after 464 ms
Starting 'browserify'...
Browserification completed.
Finished 'browserify' after 142 ms
Starting 'minify'...
'node_modules\uglify-js\bin\uglifyjs' is not recognized as an internal or external command,
operable program or batch file.
jake aborted.
Error: Command failed: node_modules\uglify-js\bin\uglifyjs ejs.js > ejs.min.js
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at exec (C:\Users\davidmoonraw\Documents\dev\foo\ejs\jakefile.js:5:3)
    at Task.action (C:\Users\davidmoonraw\Documents\dev\foo\ejs\jakefile.js:36:3)
    at Task.run (C:\Users\davidmoonraw\Documents\dev\foo\ejs\node_modules\jake\lib\task\task.js:325:29)
    at process.processImmediate (node:internal/timers:478:21)

```

**Comment by mde** [comment]
Is this happening in `main`?

**Comment by chyzwar** [comment]
try `npx jake build`
